### ISSUE TITLE
Status: gpg not in this path

### ISSUE THREAD

**Issue by Mahaaveer** [lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt#1]
Using it on windows and the path points to bin folder of Gnupg  which contains the executable. The plugin fails to detect the path

**Comment by lajg-dev** [comment]
Thanks for time your time and create this Issue,
I tested in a windows machine using `C:\Program Files (x86)\GnuPG\bin\gpg.exe` as path, and it works for me, please give more details, the path that you used and a screenshot to fix the issue, thanks
![Screenshot 2024-03-03 at 10 28 00 AM](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/44793127/b9b36326-0c8d-41ce-ac94-448a017b96fc)

**Comment by lajg-dev** [comment]
So that the problem that happened to you does not occur to more people, I have created release [1.0.5](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/releases/tag/1.0.5), where the operating system is automatically detected, and by default it places the corresponding path (According to the standard location, in case of configurations specific GnuPG would not apply and would have to be entered manually)

**Comment by Mahaaveer** [comment]
Thanks for the reply. The mistake was mine. i mistook it for path to the folder containing gpg.exe 

i had " C:\Program Files (x86)\GnuPG\bin "  in the path. adding gpg.exe works 

off-topic: the difference between this project and gpgcrypt seems to be additional base64 encode. is it to overcome obsidian's cache that shows decrypted text until we close the file?

**Comment by lajg-dev** [comment]
I'm glad this works for you, regarding the base64 issue, I did it to facilitate the live-preview of the "Secret" icon since this way the encrypted text is presented in a single line.
This plugin differs from gpgcrypt in that gpgcrypt is based on encrypting the entire document whenever it is closed and decrypting it whenever it is opened. In the case of my plugin, it encrypts and decrypts on demand either in-line or block and does not decryption is forced every time the document is opened.

**Comment by Mahaaveer** [comment]
Thanks for taking the time to explain. Closing this issue. keep up the good work.

**Comment by Mahaaveer** [comment]
An option to select the default encryption key in the settings page would be a nice enhancement.

**Comment by lajg-dev** [comment]
This function already exists within the Plugin, what you must do is start a process of encrypting a text, this will open a modal with the available GPG keys, here you must select which keys you want to encrypt the text with, then these same keys will have the option to decrypt the text, you could be guided by the image that is posted in the [readme.md](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/blob/main/README.md)
![Screenshot_03](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/assets/44793127/b4df9825-047f-4eca-9cb2-4f899e545c32)

**Comment by lajg-dev** [comment]
Thank you very much for the idea, the truth is that it would help a lot with the use of the plugin to have keys already selected by default, I have added this functionality in version [1.0.6](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/releases/tag/1.0.6) which is now available to update.

**Comment by lajg-dev** [comment]
Thank you very much for the idea, the truth is that it would help a lot with the use of the plugin to have keys already selected by default, I have added this functionality in version [1.0.6](https://github.com/lajg-dev/Obsidian-Plugin-GPG-Inline-Encrypt/releases/tag/1.0.6) which is now available to update.

**Comment by Mahaaveer** [comment]
Thanks! Indeed it would help to have default keys selected, especially if you have more keys on your keyring
